# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b089e525bc6fa2c06e47e658fff5baff6e40a7aa1d1438b5eb77c5dda1d091d29305f6d6c3185a6b7ed0e9f5d311f5ac58c7856de7ee6c67a2b3bdc4a47ec90

test:
  secret_key_base: 0a1645adf229b1ecb615b9f0bb3a96b0d0ba665d56707a14018c988008cced50435006e5eccab5ff0397af49c5f9b16f858666c0d71b1669905bed142c618d08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
